







   workflows:
     ios-workflow:
       name: iOS Workflow
       # ....
       environment:
         ios_signing:
           distribution_type: app_store # or: ad_hoc | development | enterprise
           bundle_identifier: io.testpro.koel
       scripts:
             # ... your dependencies installation
         - script: keychain initialize
         - script: keychain add-certificates
         - script: xcode-project use-profiles
         - script: flutter packages pub get
         - name : Build ipa for distribution
           script: /
             flutter build ipa --export-options-plist="---/build/ios/ipa/*.ipa"
       artifacts:
         - build/ios/ipa/*.ipa

       publishing:
         email:
           recipients:
             - limopato254@gmail.com
