







   workflows:
     ios-workflow:
       name: iOS Workflow
       # ....
       environment:
         ios_signing:
           distribution_type: app_store # or: ad_hoc | development | enterprise
           bundle_identifier: io.testpro.koel
       scripts:
             # ... your dependencies installation
         - script: keychain initialize
         - script: keychain add-certificates
         - script: xcode-project use-profiles
         - script: flutter packages pub get
         - name : Build ipa for distribution
           script: /
             flutter build ipa --export-options-plist=/users/builder/export_options.plist
       artifacts:
         - build/ios/ipa/*.ipa
         - /tmp/xcodebuild_logs/*.log
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
       publishing:
         email:
           recipients:
             - limopato254@gmail.com
